import '@fontsource/source-serif-pro/400.css'
import '@fontsource/source-serif-pro/700.css'
import '@fontsource/source-sans-pro/400.css'
import '@fontsource/source-sans-pro/400-italic.css'
import '@fontsource/source-sans-pro/700.css'
import '@popperjs/core/dist/umd/popper.min.js'
import 'bootstrap/js/dist/collapse.js'
